export const team = [
    { "id": 1, "name": "Lettie Isenor", "email": "lisenor0@pagesperso-orange.fr", "role": "Environmental Specialist" },
    { "id": 2, "name": "Alana Pressman", "email": "apressman1@livejournal.com", "role": "Senior Sales Associate" },
    { "id": 3, "name": "Ara Wooller", "email": "awooller2@nbcnews.com", "role": "Community Outreach Specialist" },
    { "id": 4, "name": "Reinhold Donovan", "email": "rdonovan3@amazon.de", "role": "Biostatistician III" },
    { "id": 5, "name": "Katha Docker", "email": "kdocker4@whitehouse.gov", "role": "Systems Administrator IV" },
    { "id": 6, "name": "Nanette Tuftin", "email": "ntuftin5@economist.com", "role": "Nurse" },
    { "id": 7, "name": "Gizela Hoggetts", "email": "ghoggetts6@aboutads.info", "role": "Software Consultant" },
    { "id": 8, "name": "Christie Tolmie", "email": "ctolmie7@taobao.com", "role": "Account Coordinator" },
    { "id": 9, "name": "Leon Maxted", "email": "lmaxted8@issuu.com", "role": "VP Quality Control" },
    { "id": 10, "name": "Kurtis Bowditch", "email": "kbowditch9@techcrunch.com", "role": "Tax Accountant" },
    { "id": 11, "name": "Ciro Gerrels", "email": "cgerrelsa@msu.edu", "role": "Software Test Engineer IV" },
    { "id": 12, "name": "Livvyy Gary", "email": "lgaryb@zdnet.com", "role": "Registered Nurse" },
    { "id": 13, "name": "Becka Scurrey", "email": "bscurreyc@phpbb.com", "role": "Desktop Support Technician" },
    { "id": 14, "name": "Vitoria Pardi", "email": "vpardid@behance.net", "role": "Nurse" },
    { "id": 15, "name": "Jacqui Luckwell", "email": "jluckwelle@vkontakte.ru", "role": "Recruiter" },
    { "id": 16, "name": "Doria Devigne", "email": "ddevignef@webs.com", "role": "Help Desk Operator" },
    { "id": 17, "name": "Teodora Perrelli", "email": "tperrellig@amazon.co.jp", "role": "Analyst Programmer" },
    { "id": 18, "name": "Tremaine Kinchin", "email": "tkinchinh@who.int", "role": "Junior Executive" },
    { "id": 19, "name": "Marney Doidge", "email": "mdoidgei@nasa.gov", "role": "Accountant IV" },
    { "id": 20, "name": "Valery Crackett", "email": "vcrackettj@plala.or.jp", "role": "Operator" },
    { "id": 21, "name": "Cindie Mayow", "email": "cmayowk@abc.net.au", "role": "Occupational Therapist" },
    { "id": 22, "name": "Bing Blazic", "email": "bblazicl@cbc.ca", "role": "Environmental Tech" },
    { "id": 23, "name": "Walton Colisbe", "email": "wcolisbem@springer.com", "role": "Developer II" },
    { "id": 24, "name": "Amerigo Ambrozik", "email": "aambrozikn@unc.edu", "role": "Design Engineer" },
    { "id": 25, "name": "Dasha Sansbury", "email": "dsansburyo@va.gov", "role": "Technical Writer" },
    { "id": 26, "name": "Iormina Grass", "email": "igrassp@ezinearticles.com", "role": "Developer I" },
    { "id": 27, "name": "Heath Redmire", "email": "hredmireq@livejournal.com", "role": "Software Test Engineer I" },
    { "id": 28, "name": "Zarla Cuff", "email": "zcuffr@ifeng.com", "role": "Quality Control Specialist" },
    { "id": 29, "name": "Cori Rutter", "email": "crutters@cpanel.net", "role": "Payment Adjustment Coordinator" },
    { "id": 30, "name": "Melissa Bolver", "email": "mbolvert@arstechnica.com", "role": "Clinical Specialist" },
    { "id": 31, "name": "Carrissa Bradly", "email": "cbradlyu@yale.edu", "role": "Senior Financial Analyst" },
    { "id": 32, "name": "Genvieve Rosenschein", "email": "grosenscheinv@wufoo.com", "role": "Tax Accountant" },
    { "id": 33, "name": "Arlee Looney", "email": "alooneyw@statcounter.com", "role": "Structural Engineer" },
    { "id": 34, "name": "Cal Flannery", "email": "cflanneryx@telegraph.co.uk", "role": "Assistant Media Planner" },
    { "id": 35, "name": "Toddy O'Hingerty", "email": "tohingertyy@auda.org.au", "role": "Mechanical Systems Engineer" },
    { "id": 36, "name": "Jackie Scambler", "email": "jscamblerz@hugedomains.com", "role": "Accountant I" },
    { "id": 37, "name": "Angus Rebert", "email": "arebert10@sitemeter.com", "role": "Data Coordiator" },
    { "id": 38, "name": "Dalia Defond", "email": "ddefond11@bing.com", "role": "Account Representative II" },
    { "id": 39, "name": "Moore Togwell", "email": "mtogwell12@cbc.ca", "role": "Accountant II" },
    { "id": 40, "name": "Brand Isherwood", "email": "bisherwood13@sohu.com", "role": "Health Coach I" },
    { "id": 41, "name": "Webster Salvador", "email": "wsalvador14@jimdo.com", "role": "Occupational Therapist" },
    { "id": 42, "name": "Reina Suttling", "email": "rsuttling15@slashdot.org", "role": "Media Manager III" },
    { "id": 43, "name": "Sisely Doring", "email": "sdoring16@wikia.com", "role": "Programmer Analyst III" },
    { "id": 44, "name": "Deina Getten", "email": "dgetten17@amazon.co.jp", "role": "Food Chemist" },
    { "id": 45, "name": "Violante Blodgetts", "email": "vblodgetts18@cnbc.com", "role": "Graphic Designer" },
    { "id": 46, "name": "Richie Rattray", "email": "rrattray19@omniture.com", "role": "Dental Hygienist" },
    { "id": 47, "name": "Meryl Weir", "email": "mweir1a@fotki.com", "role": "Professor" },
    { "id": 48, "name": "Natalina Neilands", "email": "nneilands1b@comsenz.com", "role": "Senior Financial Analyst" },
    { "id": 49, "name": "Russ Whittington", "email": "rwhittington1c@a8.net", "role": "Web Designer III" },
    { "id": 50, "name": "Joycelin Winstanley", "email": "jwinstanley1d@omniture.com", "role": "Recruiting Manager" }
];

export const roles = [
    {"role":"Junior Executive"},
    {"role":"Quality Control Specialist"},
    {"role":"Compensation Analyst"},
    {"role":"Staff Scientist"},
    {"role":"Financial Advisor"},
    {"role":"Pharmacist"},
    {"role":"Senior Financial Analyst"},
    {"role":"Tax Accountant"},
    {"role":"Financial Advisor"},
    {"role":"Mechanical Systems Engineer"},
    {"role":"Administrative Assistant II"},
    {"role":"Financial Advisor"},
    {"role":"Automation Specialist I"},
    {"role":"Nuclear Power Engineer"},
    {"role":"Tax Accountant"},
    {"role":"Assistant Media Planner"},
    {"role":"Marketing Manager"},
    {"role":"Design Engineer"},
    {"role":"Internal Auditor"},
    {"role":"Actuary"},
    {"role":"Occupational Therapist"},
    {"role":"Research Assistant IV"},
    {"role":"Tax Accountant"},
    {"role":"Help Desk Technician"},
    {"role":"Senior Sales Associate"},
    {"role":"Chemical Engineer"},
    {"role":"Senior Financial Analyst"},
    {"role":"Chemical Engineer"},
    {"role":"Nurse"},
    {"role":"Community Outreach Specialist"},
    {"role":"Quality Engineer"},
    {"role":"Geological Engineer"},
    {"role":"Staff Accountant I"},
    {"role":"Database Administrator II"},
    {"role":"Recruiter"},
    {"role":"Human Resources Manager"},
    {"role":"Desktop Support Technician"},
    {"role":"Senior Editor"},
    {"role":"Project Manager"},
    {"role":"Staff Scientist"},
    {"role":"Accountant IV"},
    {"role":"Product Engineer"},
    {"role":"Account Executive"},
    {"role":"Paralegal"},
    {"role":"Clinical Specialist"},
    {"role":"Assistant Media Planner"},
    {"role":"Business Systems Development Analyst"},
    {"role":"Quality Control Specialist"},
    {"role":"Product Engineer"},
    {"role":"Office Assistant III"}
];